name: Copy files to different repo

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: ''
        destination_repo: 'xmtp/xmtp-dot-org'
        destination_folder: 'docs'
        destination_branch: 'main'
        user_email: 'jha@xmtp.com'
        user_name: 'jhaaaa'
        commit_message: 'Copying files'